const DEFAULT_CONSTS = {
	TRACK_TITLE_MAX_LENGTH: 40,
	TRACK_AUTHOR_MAX_LENGTH: 15,
	TRACK_DESCRIPTION_MAX_LENGTH: 300,
	TRACK_TAGS_MAX: 5,
	MIN_PREV_TRACKS_TO_SHOW: 3,
	MAX_NEXT_TRACKS_TO_SHOW: 6,
};

module.exports = DEFAULT_CONSTS;
